name: CI

on:
  push:
    branches:
      - '**'
  pull_request:

concurrency:
  # This ensures runs are grouped by PR or by branch
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    # Use the relative path to your reusable workflow
    uses: ./.github/workflows/build-and-test.yml
    with:
      java-version: '21'
      python-version: '3.11'
